esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

esphome:
  name: megadesk
  comment: ESPHome Device controlling Megadesk controller
  platformio_options:
    board_build.flash_mode: dio # If you don't specify this using esp-idf framework, the device will boot-loop.

logger:
  # Use the ESP32-C3-MINI's native USB port for serial logging. Comment this out if you want to use the pin header.
  # Seems buggy.
  hardware_uart: USB_SERIAL_JTAG

external_components:
  - source: components
  #  components: [ megadesk ]
  #- source: github://gcormier/megadesk_companion/esphome@main
  #  components: [ megadesk ]
  #  refresh: 0s

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Desk Fallback Hotspot"
    password: "xxxxxxxxxx"

captive_portal:

web_server:
  port: 80

uart:
  id: uart_desk
  baud_rate: 115200
  tx_pin: GPIO6
  rx_pin: GPIO7

sensor:
  - platform: megadesk
    max_height:
      name: "Max Height"
    min_height:
      name: "Min Height"
    raw_height:
      name: "Raw Height"
#    height_cm:
      #name: "Height (cm)"
    #height_inches:
      #name: "Height (in)"


button:
  - platform: template
    name: "Desk Position 2"
    on_press:
      then:
        - uart.write: "<L0,2."
  - platform: template
    name: "Desk Position 3"
    on_press:
      then:
        - uart.write: "<L0,3."
  - platform: template
    name: "Desk Position 4"
    on_press:
      then:
        - uart.write: "<L0,4."
  - platform: template
    name: "Desk Position 5"
    on_press:
      then:
        - uart.write: "<L0,5."
  - platform: template
    name: "Toggle Minimum Desk Height"
    on_press:
      then:
        - uart.write: "<L0,11."
        - uart.write: "<R0,11."
  - platform: template
    name: "Toggle Maximum Desk Height"
    on_press:
      then:
        - uart.write: "<L0,12."
        - uart.write: "<R0,12."
  - platform: template
    name: "Recalibrate Desk"
    on_press:
      then:
        - uart.write: "<L0,14."
  - platform: template
    name: "Reboot Megadesk"
    on_press:
      then:
        - uart.write: "<L0,15."
  - platform: template
    name: "Toggle Audio feedback"
    on_press:
      then:
        - uart.write: "<L0,17."
  - platform: template
    name: "Toggle both-button mode"
    on_press:
      then:
        - uart.write: "<L0,18."

# Periodically update values every 5 minutes. Probably not needed?
interval:
  - interval: 300s
    then:
      - uart.write: "<C0.0."